name: bandit
on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  bandit:
    runs-on: ubuntu-latest
    name: bandit code scanning
    steps:
    - name: Checkout the code
      uses: actions/checkout@v2
    - name: Bandit Check
      uses: jpetrucciani/bandit-check@1.6.2
    - name: Security check report artifacts
      uses: actions/upload-artifact@v1
      # if: failure()
      with:
        name: Security report
        path: output/security_report.txt
